### PR TITLE
Enable constraints for service placement

### PR DESCRIPTION
**Pull request by ddingel**
## Description
Constraints can be passed to the service creation. We don't do any validation before pushing that to the swarm cluster.

## Motivation and Context

[Feature request: Support service placement constraints](https://github.com/alexellis/jaas/issues/4)

## How Has This Been Tested?
I tested local on a mac and also with a swarm cluster with multiple nodes and different labels.
Also I compared the `docker service inspect` output.
You can run test it with:
`./jaas -constraint "engine.labels.x == y" -constraint "node.role == manager"  -registryAuth $encAuth -rm -image nginx`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
I agree - thanks for providing a quick implementation of this. Please read the contribution guide an make sure you are happy with the DCO.

**Comment by ddingel** [comment]
Thanks for the feedback, I updated the pull request.

To be honest I am not sure regarding that pull request template:
- What documentation do you have in mind, README.md or something else?
- Currently there are no tests, are there plans to include them?

**Comment by alexellis** [comment]
From here onwards - https://github.com/alexellis/jaas/blob/master/CONTRIBUTING.md#license

Documentation can be in the README file yes.

**Comment by alexellis** [comment]
@ddingel ping.. ^

**Pull request merged**
